package main

const (
	HKHost = "18.162.41.12"
	HKUser = "internal-proxy"
	HKKey = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAn/4CpbtTj8NWURzl3dXQfADMRWRGGODRk8lS+XoW4HQAAAKCEI66whCOu
sAAAAAtzc2gtZWQyNTUxOQAAACAn/4CpbtTj8NWURzl3dXQfADMRWRGGODRk8lS+XoW4HQ
AAAEBXGLI2VgrkOcbyn+brRHRQqSgFmNYE/YlvLT0kJkfCZif/gKlu1OPw1ZRHOXd1dB8A
MxFZEYY4NGTyVL5ehbgdAAAAFmludGVybmFsLXByb3h5LXNzaC1rZXkBAgMEBQYH
-----END OPENSSH PRIVATE KEY-----`

	MXGHost = "78.12.26.238"
	MXGUser = "ec2-user"
	MXGKey  = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
c2gtZWQyNTUxOQAAACBxsibfqp4ANMpL4qwbmoARicKva8MhUNNm+mLPY2j7MwAA
AIjk0RwI5NEcCAAAAAtzc2gtZWQyNTUxOQAAACBxsibfqp4ANMpL4qwbmoARicKv
a8MhUNNm+mLPY2j7MwAAAEAwUQIBATAFBgMrZXAEIgQgFWrWH+mMdjaauc9K5PrT
6HGyJt+qngA0ykvirBuagBGJwq9rwyFQ02b6Ys9jaPszAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----`
)
