package main

const (
	XGHost = "43.199.240.15"
	XGUser = "hexu"
	XGKey  = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAN/PN7Q89q5Unm+gpt0su2VvY7UgDx7nNkArakAEJufwAAAJB6U2dcelNn
XAAAAAtzc2gtZWQyNTUxOQAAACAN/PN7Q89q5Unm+gpt0su2VvY7UgDx7nNkArakAEJufw
AAAEDZE5VlRKkSUhTu0n9xzOJgMGy2Ln1TQ+38E9e6/hTTSQ3883tDz2rlSeb6Cm3Sy7ZW
9jtSAPHuc2QCtqQAQm5/AAAADGhleHUtc3NoLWtleQE=
-----END OPENSSH PRIVATE KEY-----`

	MXGHost = "78.12.26.238"
	MXGUser = "ec2-user"
	MXGKey  = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
c2gtZWQyNTUxOQAAACBxsibfqp4ANMpL4qwbmoARicKva8MhUNNm+mLPY2j7MwAA
AIjk0RwI5NEcCAAAAAtzc2gtZWQyNTUxOQAAACBxsibfqp4ANMpL4qwbmoARicKv
a8MhUNNm+mLPY2j7MwAAAEAwUQIBATAFBgMrZXAEIgQgFWrWH+mMdjaauc9K5PrT
6HGyJt+qngA0ykvirBuagBGJwq9rwyFQ02b6Ys9jaPszAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----`
)
